package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

/**
 * Carts generated by hbm2java
 */
public class CartInfo {

	private Integer id;
	private int productId;
	private String productName;
	private UserInfo users;
	private int quantity;
	private double price;
	private Date created;	
	
	public CartInfo() {
		super();
	}
	public CartInfo(Integer id, int productId, String productName, UserInfo users, int quantity, double price,
			Date created) {
		super();
		this.id = id;
		this.productId = productId;
		this.productName = productName;
		this.users = users;
		this.quantity = quantity;
		this.price = price;
		this.created = created;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getProductId() {
		return productId;
	}
	public void setProductId(int productId) {
		this.productId = productId;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public UserInfo getUsers() {
		return users;
	}
	public void setUsers(UserInfo users) {
		this.users = users;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}

	
}
