package com.demo.models;

public class CategoryInfo {

	private int id;
	private String name;
	private double discount_percent;
	
	private Integer parentId;
	private String parentName;

	private boolean status;
	
	private int level;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Integer getParentId() {
		return parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	public boolean isStatus() {
		return status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}
	
	public String getParentName() {
		return parentName;
	}

	public void setParentName(String parentName) {
		this.parentName = parentName;
	}
	
	public int getLevel() {
		return level;
	}


import org.springframework.lang.Nullable;

// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final
/**
 * Categories generated by hbm2java
 */
public class CategoryInfo{

	private Integer id;
	@Nullable
	private int parentId;
	private double discountPercent;
	private String name;
	private boolean status;
	private int level;
	
	
	public CategoryInfo() {
		super();
	}
	public CategoryInfo(Integer id, int parentId, double discountPercent, String name, boolean status, int level) {
		super();
		this.id = id;
		this.parentId = parentId;
		this.discountPercent = discountPercent;
		this.name = name;
		this.status = status;
		this.level = level;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getParentId() {
		return parentId;
	}
	@Nullable
	public void setParentId(int parentId) {
		this.parentId = parentId;
	}
	public double getDiscountPercent() {
		return discountPercent;
	}
	public void setDiscountPercent(double discountPercent) {
		this.discountPercent = discountPercent;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isStatus() {
		return status;
	}
	public void setStatus(boolean status) {
		this.status = status;
	}
	public int getLevel() {
		return level;
	}

	public void setLevel(int level) {
		this.level = level;
	}
	

	public double getDiscount_percent() {
		return discount_percent;
	}

	public void setDiscount_percent(double discount_percent) {
		this.discount_percent = discount_percent;
	}

	public CategoryInfo() {
		super();
		// TODO Auto-generated constructor stub
	}
	
	
	
	public CategoryInfo(int id, String name, double discount_percent, Integer parentId, boolean status, int level) {
		super();
		this.id = id;
		this.name = name;
		this.discount_percent = discount_percent;
		this.parentId = parentId;
		this.status = status;
		this.level = level;
	}

	public CategoryInfo(int id, String name, Integer parentId, boolean status) {
		super();
		this.id = id;
		this.name = name;
		this.parentId = parentId;
		this.status = status;
	}
	
	public CategoryInfo(int id, String name, Integer parentId, boolean status, int level) {
		super();
		this.id = id;
		this.name = name;
		this.parentId = parentId;
		this.status = status;
		this.level = level;
	}

}
