package com.demo.models;

import org.springframework.lang.Nullable;

// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final
/**
 * Categories generated by hbm2java
 */
public class CategoryInfo{

	private Integer id;
	@Nullable
	private int parentId;
	private double discountPercent;
	private String name;
	private boolean status;
	private int level;
	
	
	public CategoryInfo() {
		super();
	}
	public CategoryInfo(Integer id, int parentId, double discountPercent, String name, boolean status, int level) {
		super();
		this.id = id;
		this.parentId = parentId;
		this.discountPercent = discountPercent;
		this.name = name;
		this.status = status;
		this.level = level;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getParentId() {
		return parentId;
	}
	@Nullable
	public void setParentId(int parentId) {
		this.parentId = parentId;
	}
	public double getDiscountPercent() {
		return discountPercent;
	}
	public void setDiscountPercent(double discountPercent) {
		this.discountPercent = discountPercent;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public boolean isStatus() {
		return status;
	}
	public void setStatus(boolean status) {
		this.status = status;
	}
	public int getLevel() {
		return level;
	}
	public void setLevel(int level) {
		this.level = level;
	}
	
	
	

}
