package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

/**
 * ChatChanels generated by hbm2java
 */
public class ChatChanelInfo{

	private Integer id;
	private int storeId;
	private String storeName;
	private int userId;
	private String userName;
	
	
	public ChatChanelInfo() {
		super();
	}
	public ChatChanelInfo(Integer id, int storeId, String storeName, int userId, String userName) {
		super();
		this.id = id;
		this.storeId = storeId;
		this.storeName = storeName;
		this.userId = userId;
		this.userName = userName;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getStoreId() {
		return storeId;
	}
	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}
	public String getStoreName() {
		return storeName;
	}
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}

	

}
