package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * ChatMessages generated by hbm2java
 */
public class ChatMessageInfo{

	private Integer id;
	private int storeId;
	private String storeName;
	private int userId;
	private String userName;
	private boolean isUserSender;
	@JsonFormat(pattern = "dd/MM/yyyy")
	private Date timeSent;
	private String content;
	
	
	public ChatMessageInfo() {
		super();
	}
	public ChatMessageInfo(Integer id, int storeId, String storeName, int userId, String userName, boolean isUserSender,
			Date timeSent, String content) {
		super();
		this.id = id;
		this.storeId = storeId;
		this.storeName = storeName;
		this.userId = userId;
		this.userName = userName;
		this.isUserSender = isUserSender;
		this.timeSent = timeSent;
		this.content = content;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getStoreId() {
		return storeId;
	}
	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}
	public String getStoreName() {
		return storeName;
	}
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public boolean isUserSender() {
		return isUserSender;
	}
	public void setUserSender(boolean isUserSender) {
		this.isUserSender = isUserSender;
	}
	public Date getTimeSent() {
		return timeSent;
	}
	public void setTimeSent(Date timeSent) {
		this.timeSent = timeSent;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}

	

}
