package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * Comments generated by hbm2java
 */
public class CommentInfo{

	private Integer id;
	private int productId;
	private String productName;
	private int userId;
	private String userName;
	private String content;
	private int rating;
	@JsonFormat(pattern = "dd/MM/yyyy")
	private Date created;
	
	
	public CommentInfo() {
		super();
	}
	public CommentInfo(Integer id, int productId, String productName, int userId, String userName, String content,
			int rating, Date created) {
		super();
		this.id = id;
		this.productId = productId;
		this.productName = productName;
		this.userId = userId;
		this.userName = userName;
		this.content = content;
		this.rating = rating;
		this.created = created;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getProductId() {
		return productId;
	}
	public void setProductId(int productId) {
		this.productId = productId;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public int getRating() {
		return rating;
	}
	public void setRating(int rating) {
		this.rating = rating;
	}
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}

	

}
