package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

/**
 * Notifications generated by hbm2java
 */
public class NotificationInfo{

	private Integer id;
	private int storeId;
	private String storeName;
	private int userId;
	private String userName;
	private String content;
	private Date created;
	private boolean isRead;
	private boolean isAllUser;
	private boolean isAllStore;
	
	
	public NotificationInfo() {
		super();
	}
	public NotificationInfo(Integer id, int storeId, String storeName, int userId, String userName, String content,
			Date created, boolean isRead, boolean isAllUser, boolean isAllStore) {
		super();
		this.id = id;
		this.storeId = storeId;
		this.storeName = storeName;
		this.userId = userId;
		this.userName = userName;
		this.content = content;
		this.created = created;
		this.isRead = isRead;
		this.isAllUser = isAllUser;
		this.isAllStore = isAllStore;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getStoreId() {
		return storeId;
	}
	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}
	public String getStoreName() {
		return storeName;
	}
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}
	public boolean isRead() {
		return isRead;
	}
	public void setRead(boolean isRead) {
		this.isRead = isRead;
	}
	public boolean isAllUser() {
		return isAllUser;
	}
	public void setAllUser(boolean isAllUser) {
		this.isAllUser = isAllUser;
	}
	public boolean isAllStore() {
		return isAllStore;
	}
	public void setAllStore(boolean isAllStore) {
		this.isAllStore = isAllStore;
	}

	

}
