package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

/**
 * TagProducts generated by hbm2java
 */
public class TagProductInfo{

	private Integer id;
	private int  productId;
	private String  productName;
	private int tagId;
	private String tagName;
	
	
	public TagProductInfo() {
		super();
	}
	public TagProductInfo(Integer id, int productId, String productName, int tagId, String tagName) {
		super();
		this.id = id;
		this.productId = productId;
		this.productName = productName;
		this.tagId = tagId;
		this.tagName = tagName;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getProductId() {
		return productId;
	}
	public void setProductId(int productId) {
		this.productId = productId;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public int getTagId() {
		return tagId;
	}
	public void setTagId(int tagId) {
		this.tagId = tagId;
	}
	public String getTagName() {
		return tagName;
	}
	public void setTagName(String tagName) {
		this.tagName = tagName;
	}

	

}
