package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

/**
 * Transactions generated by hbm2java
 */
public class TransactionInfo{

	private Integer id;
	private int productId;
	private String productName;
	private int serviceId;
	private String serviceName;
	private int storeId;
	private String storeName;
	private int transactionDetailId;
	private String transactionDetailName;
	private double price;
	private int quantity;
	private double tax;
	private double total;
	private String note;
	private boolean status;
	private String cancelReason;
	
	
	public TransactionInfo() {
		super();
	}
	
	
	
	public TransactionInfo(Integer id, int serviceId, String serviceName, int storeId, String storeName,
			int transactionDetailId, String transactionDetailName, double price, int quantity, double tax, double total,
			boolean status) {
		super();
		this.id = id;
		this.serviceId = serviceId;
		this.serviceName = serviceName;
		this.storeId = storeId;
		this.storeName = storeName;
		this.transactionDetailId = transactionDetailId;
		this.transactionDetailName = transactionDetailName;
		this.price = price;
		this.quantity = quantity;
		this.tax = tax;
		this.total = total;
		this.status = status;
	}



	public TransactionInfo(Integer id, int productId, String productName, int storeId, String storeName,
			int transactionDetailId, String transactionDetailName, double price, int quantity, double tax, double total,
			String note, boolean status) {
		super();
		this.id = id;
		this.productId = productId;
		this.productName = productName;
		this.storeId = storeId;
		this.storeName = storeName;
		this.transactionDetailId = transactionDetailId;
		this.transactionDetailName = transactionDetailName;
		this.price = price;
		this.quantity = quantity;
		this.tax = tax;
		this.total = total;
		this.note = note;
		this.status = status;
	}

	public TransactionInfo(Integer id, int productId, String productName, int serviceId, String serviceName,
			int storeId, String storeName, int transactionDetailId, String transactionDetailName, double price,
			int quantity, double tax, double total, String note, boolean status, String cancelReason) {
		super();
		this.id = id;
		this.productId = productId;
		this.productName = productName;
		this.serviceId = serviceId;
		this.serviceName = serviceName;
		this.storeId = storeId;
		this.storeName = storeName;
		this.transactionDetailId = transactionDetailId;
		this.transactionDetailName = transactionDetailName;
		this.price = price;
		this.quantity = quantity;
		this.tax = tax;
		this.total = total;
		this.note = note;
		this.status = status;
		this.cancelReason = cancelReason;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getProductId() {
		return productId;
	}
	public void setProductId(int productId) {
		this.productId = productId;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public int getServiceId() {
		return serviceId;
	}
	public void setServiceId(int serviceId) {
		this.serviceId = serviceId;
	}
	public String getServiceName() {
		return serviceName;
	}
	public void setServiceName(String serviceName) {
		this.serviceName = serviceName;
	}
	public int getStoreId() {
		return storeId;
	}
	public void setStoreId(int storeId) {
		this.storeId = storeId;
	}
	public String getStoreName() {
		return storeName;
	}
	public void setStoreName(String storeName) {
		this.storeName = storeName;
	}
	public int getTransactionDetailId() {
		return transactionDetailId;
	}
	public void setTransactionDetailId(int transactionDetailId) {
		this.transactionDetailId = transactionDetailId;
	}
	public String getTransactionDetailName() {
		return transactionDetailName;
	}
	public void setTransactionDetailName(String transactionDetailName) {
		this.transactionDetailName = transactionDetailName;
	}
	public double getPrice() {
		return price;
	}
	public void setPrice(double price) {
		this.price = price;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public double getTax() {
		return tax;
	}
	public void setTax(double tax) {
		this.tax = tax;
	}
	public double getTotal() {
		return total;
	}
	public void setTotal(double total) {
		this.total = total;
	}
	public String getNote() {
		return note;
	}
	public void setNote(String note) {
		this.note = note;
	}
	public boolean isStatus() {
		return status;
	}
	public void setStatus(boolean status) {
		this.status = status;
	}
	public String getCancelReason() {
		return cancelReason;
	}
	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

	

}
