package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Banners generated by hbm2java
 */
public class Banners implements java.io.Serializable {

	private Integer id;
	private Users usersByCreaterId;
	private Users usersByUpdaterId;
	private String caption;
	private String description;
	private String link;
	private Date created;
	private Date updated;
	private boolean status;
	private Set imageses = new HashSet(0);

	public Banners() {
	}

	public Banners(Users usersByCreaterId, Users usersByUpdaterId, String caption, String description, String link,
			Date created, Date updated, boolean status) {
		this.usersByCreaterId = usersByCreaterId;
		this.usersByUpdaterId = usersByUpdaterId;
		this.caption = caption;
		this.description = description;
		this.link = link;
		this.created = created;
		this.updated = updated;
		this.status = status;
	}

	public Banners(Users usersByCreaterId, Users usersByUpdaterId, String caption, String description, String link,
			Date created, Date updated, boolean status, Set imageses) {
		this.usersByCreaterId = usersByCreaterId;
		this.usersByUpdaterId = usersByUpdaterId;
		this.caption = caption;
		this.description = description;
		this.link = link;
		this.created = created;
		this.updated = updated;
		this.status = status;
		this.imageses = imageses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUsersByCreaterId() {
		return this.usersByCreaterId;
	}

	public void setUsersByCreaterId(Users usersByCreaterId) {
		this.usersByCreaterId = usersByCreaterId;
	}

	public Users getUsersByUpdaterId() {
		return this.usersByUpdaterId;
	}

	public void setUsersByUpdaterId(Users usersByUpdaterId) {
		this.usersByUpdaterId = usersByUpdaterId;
	}

	public String getCaption() {
		return this.caption;
	}

	public void setCaption(String caption) {
		this.caption = caption;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getLink() {
		return this.link;
	}

	public void setLink(String link) {
		this.link = link;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public Set getImageses() {
		return this.imageses;
	}

	public void setImageses(Set imageses) {
		this.imageses = imageses;
	}

}
