package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Branchs generated by hbm2java
 */
public class Branchs implements java.io.Serializable {

	private Integer id;
	private String name;
	private String logo;
	private Set productses = new HashSet(0);

	public Branchs() {
	}

	public Branchs(String name, String logo) {
		this.name = name;
		this.logo = logo;
	}

	public Branchs(String name, String logo, Set productses) {
		this.name = name;
		this.logo = logo;
		this.productses = productses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getLogo() {
		return this.logo;
	}

	public void setLogo(String logo) {
		this.logo = logo;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
