package com.demo.entities;
<<<<<<< HEAD
// Generated Nov 16, 2021, 9:57:26 AM by Hibernate Tools 5.1.10.Final
=======
// Generated Nov 16, 2021, 9:02:55 AM by Hibernate Tools 5.1.10.Final
>>>>>>> 9fd1d1ca7d86be0f207fb63535de461072b91dc7

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Carts generated by hbm2java
 */
@Entity
@Table(name = "carts", catalog = "ecommerce_db")
public class Carts implements java.io.Serializable {

	private Integer id;
	private Products products;
	private Users users;
	private int quantity;
	private double price;
	private Date created;

	public Carts() {
	}

	public Carts(Products products, Users users, int quantity, double price, Date created) {
		this.products = products;
		this.users = users;
		this.quantity = quantity;
		this.price = price;
		this.created = created;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false)
	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "price", nullable = false, precision = 22, scale = 0)
	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "created", nullable = false, length = 10)
	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
