package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * Carts generated by hbm2java
 */
public class Carts implements java.io.Serializable {

	private Integer id;
	private Products products;
	private Users users;
	private int quantity;
	private double price;
	private Date created;

	public Carts() {
	}

	public Carts(Products products, Users users, int quantity, double price, Date created) {
		this.products = products;
		this.users = users;
		this.quantity = quantity;
		this.price = price;
		this.created = created;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
