package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Categories generated by hbm2java
 */
public class Categories implements java.io.Serializable {

	private Integer id;
	private Categories categories;
	private String name;
	private boolean status;
	private Set categorieses = new HashSet(0);
	private Set productses = new HashSet(0);

	public Categories() {
	}

	public Categories(Categories categories, String name, boolean status) {
		this.categories = categories;
		this.name = name;
		this.status = status;
	}

	public Categories(Categories categories, String name, boolean status, Set categorieses, Set productses) {
		this.categories = categories;
		this.name = name;
		this.status = status;
		this.categorieses = categorieses;
		this.productses = productses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public Set getCategorieses() {
		return this.categorieses;
	}

	public void setCategorieses(Set categorieses) {
		this.categorieses = categorieses;
	}

	public Set getProductses() {
		return this.productses;
	}

	public void setProductses(Set productses) {
		this.productses = productses;
	}

}
