package com.demo.entities;
<<<<<<< HEAD
// Generated Nov 16, 2021, 9:57:26 AM by Hibernate Tools 5.1.10.Final
=======
// Generated Nov 16, 2021, 9:02:55 AM by Hibernate Tools 5.1.10.Final
>>>>>>> 9fd1d1ca7d86be0f207fb63535de461072b91dc7

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categories generated by hbm2java
 */
@Entity
@Table(name = "categories", catalog = "ecommerce_db")
public class Categories implements java.io.Serializable {

	private Integer id;
	private Categories categories;
	private String name;
	private boolean status;
	private Set<Categories> categorieses = new HashSet<Categories>(0);
	private Set<Products> productses = new HashSet<Products>(0);

	public Categories() {
	}

	public Categories(String name, boolean status) {
		this.name = name;
		this.status = status;
	}

	public Categories(Categories categories, String name, boolean status, Set<Categories> categorieses,
			Set<Products> productses) {
		this.categories = categories;
		this.name = name;
		this.status = status;
		this.categorieses = categorieses;
		this.productses = productses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
<<<<<<< HEAD
	@JoinColumn(name = "parent_id")
=======
	@JoinColumn(name = "parent_id", nullable = false)
>>>>>>> 9fd1d1ca7d86be0f207fb63535de461072b91dc7
	public Categories getCategories() {
		return this.categories;
	}

	public void setCategories(Categories categories) {
		this.categories = categories;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "status", nullable = false)
	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	public Set<Categories> getCategorieses() {
		return this.categorieses;
	}

	public void setCategorieses(Set<Categories> categorieses) {
		this.categorieses = categorieses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	public Set<Products> getProductses() {
		return this.productses;
	}

	public void setProductses(Set<Products> productses) {
		this.productses = productses;
	}

}
