package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

/**
 * ChatChanels generated by hbm2java
 */
public class ChatChanels implements java.io.Serializable {

	private Integer id;
	private Stores stores;
	private Users users;

	public ChatChanels() {
	}

	public ChatChanels(Stores stores, Users users) {
		this.stores = stores;
		this.users = users;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Stores getStores() {
		return this.stores;
	}

	public void setStores(Stores stores) {
		this.stores = stores;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

}
