package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * Comments generated by hbm2java
 */
public class Comments implements java.io.Serializable {

	private Integer id;
	private Products products;
	private Users users;
	private String content;
	private int rating;
	private Date created;

	public Comments() {
	}

	public Comments(Products products, Users users, String content, int rating, Date created) {
		this.products = products;
		this.users = users;
		this.content = content;
		this.rating = rating;
		this.created = created;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public int getRating() {
		return this.rating;
	}

	public void setRating(int rating) {
		this.rating = rating;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

}
