package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

/**
 * Images generated by hbm2java
 */
public class Images implements java.io.Serializable {

	private Integer id;
	private Banners banners;
	private Products products;
	private String name;

	public Images() {
	}

	public Images(Banners banners, Products products, String name) {
		this.banners = banners;
		this.products = products;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Banners getBanners() {
		return this.banners;
	}

	public void setBanners(Banners banners) {
		this.banners = banners;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
