package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * Notifications generated by hbm2java
 */
public class Notifications implements java.io.Serializable {

	private Integer id;
	private Stores stores;
	private Users users;
	private String content;
	private Date created;
	private boolean isRead;

	public Notifications() {
	}

	public Notifications(Stores stores, Users users, String content, Date created, boolean isRead) {
		this.stores = stores;
		this.users = users;
		this.content = content;
		this.created = created;
		this.isRead = isRead;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Stores getStores() {
		return this.stores;
	}

	public void setStores(Stores stores) {
		this.stores = stores;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public boolean isIsRead() {
		return this.isRead;
	}

	public void setIsRead(boolean isRead) {
		this.isRead = isRead;
	}

}
