package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;

/**
 * Promotions generated by hbm2java
 */
public class Promotions implements java.io.Serializable {

	private Integer id;
	private Date fromDate;
	private Date toDate;
	private boolean applyForAll;
	private double discountPercent;
	private double discountAmount;
	private String productIds;
	private String categoryIds;
	private boolean status;
	private String name;

	public Promotions() {
	}

	public Promotions(Date fromDate, Date toDate, boolean applyForAll, double discountPercent, double discountAmount,
			String productIds, String categoryIds, boolean status, String name) {
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.applyForAll = applyForAll;
		this.discountPercent = discountPercent;
		this.discountAmount = discountAmount;
		this.productIds = productIds;
		this.categoryIds = categoryIds;
		this.status = status;
		this.name = name;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public boolean isApplyForAll() {
		return this.applyForAll;
	}

	public void setApplyForAll(boolean applyForAll) {
		this.applyForAll = applyForAll;
	}

	public double getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(double discountPercent) {
		this.discountPercent = discountPercent;
	}

	public double getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(double discountAmount) {
		this.discountAmount = discountAmount;
	}

	public String getProductIds() {
		return this.productIds;
	}

	public void setProductIds(String productIds) {
		this.productIds = productIds;
	}

	public String getCategoryIds() {
		return this.categoryIds;
	}

	public void setCategoryIds(String categoryIds) {
		this.categoryIds = categoryIds;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
