package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

/**
 * TagProducts generated by hbm2java
 */
public class TagProducts implements java.io.Serializable {

	private Integer id;
	private Products products;
	private Tags tags;

	public TagProducts() {
	}

	public TagProducts(Products products, Tags tags) {
		this.products = products;
		this.tags = tags;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Tags getTags() {
		return this.tags;
	}

	public void setTags(Tags tags) {
		this.tags = tags;
	}

}
