package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Tags generated by hbm2java
 */
public class Tags implements java.io.Serializable {

	private Integer id;
	private String name;
	private boolean status;
	private Set tagProductses = new HashSet(0);

	public Tags() {
	}

	public Tags(String name, boolean status) {
		this.name = name;
		this.status = status;
	}

	public Tags(String name, boolean status, Set tagProductses) {
		this.name = name;
		this.status = status;
		this.tagProductses = tagProductses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public Set getTagProductses() {
		return this.tagProductses;
	}

	public void setTagProductses(Set tagProductses) {
		this.tagProductses = tagProductses;
	}

}
