package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

/**
 * Transactions generated by hbm2java
 */
public class Transactions implements java.io.Serializable {

	private Integer id;
	private Products products;
	private Services services;
	private Stores stores;
	private TransactionDetails transactionDetails;
	private double price;
	private int quantity;
	private double tax;
	private double total;
	private String note;
	private boolean status;
	private String cancelReason;

	public Transactions() {
	}

	public Transactions(Products products, Services services, Stores stores, TransactionDetails transactionDetails,
			double price, int quantity, double tax, double total, boolean status, String cancelReason) {
		this.products = products;
		this.services = services;
		this.stores = stores;
		this.transactionDetails = transactionDetails;
		this.price = price;
		this.quantity = quantity;
		this.tax = tax;
		this.total = total;
		this.status = status;
		this.cancelReason = cancelReason;
	}

	public Transactions(Products products, Services services, Stores stores, TransactionDetails transactionDetails,
			double price, int quantity, double tax, double total, String note, boolean status, String cancelReason) {
		this.products = products;
		this.services = services;
		this.stores = stores;
		this.transactionDetails = transactionDetails;
		this.price = price;
		this.quantity = quantity;
		this.tax = tax;
		this.total = total;
		this.note = note;
		this.status = status;
		this.cancelReason = cancelReason;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

	public Services getServices() {
		return this.services;
	}

	public void setServices(Services services) {
		this.services = services;
	}

	public Stores getStores() {
		return this.stores;
	}

	public void setStores(Stores stores) {
		this.stores = stores;
	}

	public TransactionDetails getTransactionDetails() {
		return this.transactionDetails;
	}

	public void setTransactionDetails(TransactionDetails transactionDetails) {
		this.transactionDetails = transactionDetails;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public double getTax() {
		return this.tax;
	}

	public void setTax(double tax) {
		this.tax = tax;
	}

	public double getTotal() {
		return this.total;
	}

	public void setTotal(double total) {
		this.total = total;
	}

	public String getNote() {
		return this.note;
	}

	public void setNote(String note) {
		this.note = note;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public String getCancelReason() {
		return this.cancelReason;
	}

	public void setCancelReason(String cancelReason) {
		this.cancelReason = cancelReason;
	}

}
