package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TransactionDetails generated by hbm2java
 */
public class TransactionDetails implements java.io.Serializable {

	private Integer id;
	private Users users;
	private String name;
	private String payment;
	private String address;
	private int quantity;
	private double discount;
	private double vat;
	private Date created;
	private Set transactionses = new HashSet(0);

	public TransactionDetails() {
	}

	public TransactionDetails(Users users, String name, String payment, String address, int quantity, double discount,
			double vat, Date created) {
		this.users = users;
		this.name = name;
		this.payment = payment;
		this.address = address;
		this.quantity = quantity;
		this.discount = discount;
		this.vat = vat;
		this.created = created;
	}

	public TransactionDetails(Users users, String name, String payment, String address, int quantity, double discount,
			double vat, Date created, Set transactionses) {
		this.users = users;
		this.name = name;
		this.payment = payment;
		this.address = address;
		this.quantity = quantity;
		this.discount = discount;
		this.vat = vat;
		this.created = created;
		this.transactionses = transactionses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Users getUsers() {
		return this.users;
	}

	public void setUsers(Users users) {
		this.users = users;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPayment() {
		return this.payment;
	}

	public void setPayment(String payment) {
		this.payment = payment;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public double getDiscount() {
		return this.discount;
	}

	public void setDiscount(double discount) {
		this.discount = discount;
	}

	public double getVat() {
		return this.vat;
	}

	public void setVat(double vat) {
		this.vat = vat;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Set getTransactionses() {
		return this.transactionses;
	}

	public void setTransactionses(Set transactionses) {
		this.transactionses = transactionses;
	}

}
