package com.demo.entities;
// Generated Nov 15, 2021, 3:44:29 PM by Hibernate Tools 5.4.30.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private Integer id;
	private Roles roles;
	private String username;
	private String password;
	private String fullname;
	private Date birthday;
	private String phone;
	private String email;
	private Date created;
	private Date updated;
	private boolean status;
	private Set chatChanelses = new HashSet(0);
	private Set transactionDetailses = new HashSet(0);
	private Set notificationses = new HashSet(0);
	private Set cartses = new HashSet(0);
	private Set servicesesForCreatedId = new HashSet(0);
	private Set bannersesForCreaterId = new HashSet(0);
	private Set commentses = new HashSet(0);
	private Set bannersesForUpdaterId = new HashSet(0);
	private Set servicesesForUpdatedId = new HashSet(0);
	private Set storeses = new HashSet(0);
	private Set chatMessageses = new HashSet(0);

	public Users() {
	}

	public Users(Roles roles, String username, String password, String fullname, Date birthday, String phone,
			String email, Date created, Date updated, boolean status) {
		this.roles = roles;
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.birthday = birthday;
		this.phone = phone;
		this.email = email;
		this.created = created;
		this.updated = updated;
		this.status = status;
	}

	public Users(Roles roles, String username, String password, String fullname, Date birthday, String phone,
			String email, Date created, Date updated, boolean status, Set chatChanelses, Set transactionDetailses,
			Set notificationses, Set cartses, Set servicesesForCreatedId, Set bannersesForCreaterId, Set commentses,
			Set bannersesForUpdaterId, Set servicesesForUpdatedId, Set storeses, Set chatMessageses) {
		this.roles = roles;
		this.username = username;
		this.password = password;
		this.fullname = fullname;
		this.birthday = birthday;
		this.phone = phone;
		this.email = email;
		this.created = created;
		this.updated = updated;
		this.status = status;
		this.chatChanelses = chatChanelses;
		this.transactionDetailses = transactionDetailses;
		this.notificationses = notificationses;
		this.cartses = cartses;
		this.servicesesForCreatedId = servicesesForCreatedId;
		this.bannersesForCreaterId = bannersesForCreaterId;
		this.commentses = commentses;
		this.bannersesForUpdaterId = bannersesForUpdaterId;
		this.servicesesForUpdatedId = servicesesForUpdatedId;
		this.storeses = storeses;
		this.chatMessageses = chatMessageses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFullname() {
		return this.fullname;
	}

	public void setFullname(String fullname) {
		this.fullname = fullname;
	}

	public Date getBirthday() {
		return this.birthday;
	}

	public void setBirthday(Date birthday) {
		this.birthday = birthday;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreated() {
		return this.created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public Date getUpdated() {
		return this.updated;
	}

	public void setUpdated(Date updated) {
		this.updated = updated;
	}

	public boolean isStatus() {
		return this.status;
	}

	public void setStatus(boolean status) {
		this.status = status;
	}

	public Set getChatChanelses() {
		return this.chatChanelses;
	}

	public void setChatChanelses(Set chatChanelses) {
		this.chatChanelses = chatChanelses;
	}

	public Set getTransactionDetailses() {
		return this.transactionDetailses;
	}

	public void setTransactionDetailses(Set transactionDetailses) {
		this.transactionDetailses = transactionDetailses;
	}

	public Set getNotificationses() {
		return this.notificationses;
	}

	public void setNotificationses(Set notificationses) {
		this.notificationses = notificationses;
	}

	public Set getCartses() {
		return this.cartses;
	}

	public void setCartses(Set cartses) {
		this.cartses = cartses;
	}

	public Set getServicesesForCreatedId() {
		return this.servicesesForCreatedId;
	}

	public void setServicesesForCreatedId(Set servicesesForCreatedId) {
		this.servicesesForCreatedId = servicesesForCreatedId;
	}

	public Set getBannersesForCreaterId() {
		return this.bannersesForCreaterId;
	}

	public void setBannersesForCreaterId(Set bannersesForCreaterId) {
		this.bannersesForCreaterId = bannersesForCreaterId;
	}

	public Set getCommentses() {
		return this.commentses;
	}

	public void setCommentses(Set commentses) {
		this.commentses = commentses;
	}

	public Set getBannersesForUpdaterId() {
		return this.bannersesForUpdaterId;
	}

	public void setBannersesForUpdaterId(Set bannersesForUpdaterId) {
		this.bannersesForUpdaterId = bannersesForUpdaterId;
	}

	public Set getServicesesForUpdatedId() {
		return this.servicesesForUpdatedId;
	}

	public void setServicesesForUpdatedId(Set servicesesForUpdatedId) {
		this.servicesesForUpdatedId = servicesesForUpdatedId;
	}

	public Set getStoreses() {
		return this.storeses;
	}

	public void setStoreses(Set storeses) {
		this.storeses = storeses;
	}

	public Set getChatMessageses() {
		return this.chatMessageses;
	}

	public void setChatMessageses(Set chatMessageses) {
		this.chatMessageses = chatMessageses;
	}

}
