package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

/**
 * Images generated by hbm2java
 */
public class ImageInfo{

	private Integer id;
	private int bannerId;
	private int productId;
	private String productName;
	private String name;
	
	
	public ImageInfo() {
		super();
	}
	public ImageInfo(Integer id, int bannerId, int productId, String productName, String name) {
		super();
		this.id = id;
		this.bannerId = bannerId;
		this.productId = productId;
		this.productName = productName;
		this.name = name;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getBannerId() {
		return bannerId;
	}
	public void setBannerId(int bannerId) {
		this.bannerId = bannerId;
	}
	public int getProductId() {
		return productId;
	}
	public void setProductId(int productId) {
		this.productId = productId;
	}
	public String getProductName() {
		return productName;
	}
	public void setProductName(String productName) {
		this.productName = productName;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}

	

}
