package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

/**
 * Stores generated by hbm2java
 */
public class StoreInfo{

	private Integer id;
	private int userId;
	private String userName;
	private String name;
	private String phone;
	private String email;
	private String address;
	private String logo;
	private Date created;
	private Date expiry;
	private Date updated;
	private boolean status;
	private Date banTerm;
	
	
	public StoreInfo() {
		super();
	}
	public StoreInfo(Integer id, int userId, String userName, String name, String phone, String email, String address,
			String logo, Date created, Date expiry, Date updated, boolean status, Date banTerm) {
		super();
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.name = name;
		this.phone = phone;
		this.email = email;
		this.address = address;
		this.logo = logo;
		this.created = created;
		this.expiry = expiry;
		this.updated = updated;
		this.status = status;
		this.banTerm = banTerm;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPhone() {
		return phone;
	}
	public void setPhone(String phone) {
		this.phone = phone;
	}
	public String getEmail() {
		return email;
	}
	public void setEmail(String email) {
		this.email = email;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public String getLogo() {
		return logo;
	}
	public void setLogo(String logo) {
		this.logo = logo;
	}
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}
	public Date getExpiry() {
		return expiry;
	}
	public void setExpiry(Date expiry) {
		this.expiry = expiry;
	}
	public Date getUpdated() {
		return updated;
	}
	public void setUpdated(Date updated) {
		this.updated = updated;
	}
	public boolean isStatus() {
		return status;
	}
	public void setStatus(boolean status) {
		this.status = status;
	}
	public Date getBanTerm() {
		return banTerm;
	}
	public void setBanTerm(Date banTerm) {
		this.banTerm = banTerm;
	}
	
	

}
