package com.demo.models;
// Generated Nov 24, 2021, 4:10:46 PM by Hibernate Tools 5.1.10.Final

import java.util.Date;

/**
 * TransactionDetails generated by hbm2java
 */
public class TransactionDetailInfo{

	private Integer id;
	private int userId;
	private String userName;
	private String name;
	private String payment;
	private String address;
	private int quantity;
	private double discount;
	private double vat;
	private Date created;
	
	
	public TransactionDetailInfo() {
		super();
	}
	public TransactionDetailInfo(Integer id, int userId, String userName, String name, String payment, String address,
			int quantity, double discount, double vat, Date created) {
		super();
		this.id = id;
		this.userId = userId;
		this.userName = userName;
		this.name = name;
		this.payment = payment;
		this.address = address;
		this.quantity = quantity;
		this.discount = discount;
		this.vat = vat;
		this.created = created;
	}
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public int getUserId() {
		return userId;
	}
	public void setUserId(int userId) {
		this.userId = userId;
	}
	public String getUserName() {
		return userName;
	}
	public void setUserName(String userName) {
		this.userName = userName;
	}
	public String getName() {
		return name;
	}
	public void setName(String name) {
		this.name = name;
	}
	public String getPayment() {
		return payment;
	}
	public void setPayment(String payment) {
		this.payment = payment;
	}
	public String getAddress() {
		return address;
	}
	public void setAddress(String address) {
		this.address = address;
	}
	public int getQuantity() {
		return quantity;
	}
	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}
	public double getDiscount() {
		return discount;
	}
	public void setDiscount(double discount) {
		this.discount = discount;
	}
	public double getVat() {
		return vat;
	}
	public void setVat(double vat) {
		this.vat = vat;
	}
	public Date getCreated() {
		return created;
	}
	public void setCreated(Date created) {
		this.created = created;
	}
	
	
}
